name: CI/CD

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: yarn

      - name: Run the tests
        run: yarn test

      - name: Build
        run: yarn build

  deploy:

    runs-on: ubuntu-latest

    needs: build

    steps:

      - uses: actions/checkout@v3
      - run: pwd

      - name: Deploy
        run: |
          pwd
          echo "pwd end"
          git config --global user.name IvanRavinskiy
          echo "IvanRavinskiy end"
          git config --global user.email ivan.ravinskiy@gmail.com
          echo "ivan.ravinskiy@gmail.com end"
          git remote set-url origin https://${github_token}@github.com/${repository}
          echo "git remote set-url origin end"
          yarn deploy
          echo "deploy end"
        env:
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          github_token: ${{ secrets.ACTIONS_DEPLOY_ACCESS_TOKEN }}
          repository: ${{ github.repository }}
